Add controllers
Konkovmax/java-shareit pull request #1
Opened 2022-10-23 11:16 UTC by Konkovmax

Я помню, что надо максимум активность перенести из стороджа в сервис, но т.к. тут было инмемори, а надо будет переделать на ДБ вариант, то перекидывать всё мне показалось не логичным. Поэтому перенёс самое явное

2022-10-23 16:06 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +package ru.practicum.shareit.exception;
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +
И про файл настроек, ОПЯТЬ ))) `application.properties`, так как он не менялся, тоже тут напишу...

Я буду топить за то чтобы ты сразу привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели...

Соответственно - попрошу тебя этому следовать.

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    public ValidationErrorResponse onMethodArgumentNotValidException(
Зачем тут перенос, вроде помещается в одну строку всё...

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    }
Не хватает общего обработчика...

```
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
```

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    public ResponseEntity<ErrorMessage> handleException(ConflictException exception) {
Не хватает логирования, и обязательно со стектрейсом, вот так...

```
log.info("500 {}", e.getMessage(), e);
```

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            throw new NotFoundException(String.format(
Хранилище не кидает ексепшн. Это нужно делать в сервисе.

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (items.containsKey(id)) {
Эта проверка должна быть в сервисе

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return items.values().stream().filter(x -> x.getOwner().getId() == userId)
Каждую операцию желательно выносить на отдельную строку.

```
    public List<Item> getAll(int userId) {
        return items.values().stream()
                    .filter(x -> x.getOwner().getId() == userId)
                    .collect(Collectors.toList());
    }
```

Плюс не плохо было бы настроить вот такое выравнивание...

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Почему маппер только в одну сторону?

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +   private String name;
- валидация должна быть не у `Item`, а у `ItemDto`.
 - В контроллере мы принимаем не `Item`, а `ItemDto`.
 
 Как так получилось что у тебя всё наоборот!? ))
 
 Я тогда по этому поводу комментировать больше не буду, думаю тебе понятно...

2022-10-23 16:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@Valid @RequestBody User user) {
Контроллер принимает Dto модель и отдаёт её же... 
На самом деле отдавать может другую модель, но в нашем, пока простом варианте, туже самую dto и принимаем и отдаём.
Но не `User` - эта модель она entity она для хранилища.

2022-10-24 01:18 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +package ru.practicum.shareit.exception;
поправил

2022-10-24 02:10 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +
не поверишь, такая мысль у меня промелькнула... Но остановило то, что вроде как нам дали заготовку, где всё как надо.....
переделал

2022-10-24 02:13 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    public ValidationErrorResponse onMethodArgumentNotValidException(
К сожалению, как-то вразумительно ответить на этот вопрос я не смогу(
исправил

2022-10-24 03:04 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    }
У меня как-то 500-ка сама выдаётся, и я подумал смысл усложнять. Или это не тот случай?

исправил

2022-10-24 03:04 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +    public ResponseEntity<ErrorMessage> handleException(ConflictException exception) {
исправил

2022-10-24 03:49 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            throw new NotFoundException(String.format(
исправил

2022-10-24 03:49 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (items.containsKey(id)) {
исправил

2022-10-24 03:50 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return items.values().stream().filter(x -> x.getOwner().getId() == userId)
исправил

2022-10-24 03:57 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
В ТЗ есть такая фраза: "В дальнейшем можно будет добавлять в
них методы, которые нужны для обратного преобразования типов, — например,
toItem()."

из чего я сделал вывод, что нам нужно только туда, а обратно, когда-нибудь потом...

добавил и обратно

2022-10-24 04:19 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +   private String name;
переделал

2022-10-24 04:19 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@Valid @RequestBody User user) {
исправил

2022-10-24 18:45 UTC, FanaticFiz approved these changes

2022-10-28 14:56 UTC, merged