Add bookings
Konkovmax/java-shareit pull request #2
Opened 2022-11-07 11:39 UTC by Konkovmax

Получилось ввернуть всякие лямбды и предикаты. Это мне понравилось.

2022-11-09 18:24 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "start_date")
Не хватает указания что поле не может быть `null`, как в БД.
Для этого есть спец. возможность в `Column`

Проверь для всех полей которые в базе `NOT NULL`

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    start_date datetime,
Five different data types are used in PostgreSQL to store date and time data. 
These are `date`, `time`, `timestamp`, `time with time zone`, and `interval`.

Не забывай и про `NOT NULL`

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    status     varchar(255),
Для статуса реально надо такое большое текстовое поле?

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    description  varchar(512),
512 как для описания маловато...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    description  varchar(255)                            NOT NULL,
255 мало как для описания!

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    created      date,
Тоже замечание к дате как и к другим, ставь `TIMESTAMP WITHOUT TIME ZONE`

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @ManyToOne()
@ManyToOne() -> @ManyToOne

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getAll(userId, state, false);
Лучше иметь отдельный метод чем в одном методе задавать флаги.
Довольно тонкий момент, чтобы пояснить сейчас, но думаю ты можешь встретить такую рекомендацию много где и в книгах и в лекциях...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private void throwIfNotValid(BookingIncomeDto booking) throws BadRequestException {
Приватные методы ниже публичных. 

Не писал я тебе о порядке расположения методов? не помню...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (userRepository.findById(userId).isEmpty()) {
Не верно работаешь с `Optional` пользуйся методом `orElseThrow`

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        try {
Ну невозможно таким получением state засорять основной код... придумай чёнить! ))

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .filter(bookingStatus)
Нельзя доставать ВСЁ а потом в коде фильтровать!
У тебя же БД! Построй правильный запрос с нужными фильтрами это будет гораздо быстрее...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/UnsupportedStatusException.java
> +public class UnsupportedStatusException extends RuntimeException {
Не нужен такой класс.. Это всё частные случаи BadRequestException, который у тебя уже есть!

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +        log.info("400 Bad Request Error", exception.getMessage(), exception);
Ты в логере не в теле не добавляешь шаблон `{}` он не будет наполнен сообщением из ошибки.

`log.info("400 Bad Request Error: {}", exception.getMessage(), exception);`

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.findById(userId).get());
Нельзя прятать главное действие: вызов `userRepository.findById` куда то в сеттер...
Код надо построить наоборот.
Тем более что у тебя возвращается Optional и ты не имеешь права брать get() из него без проверки.

Попробуй перестроить код, а я потом подскажу если что...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(itemRepository.save(ItemMapper.toItem(item)));
То же самое с `itemRepository.save`
Это главное действие тут: оно должно быть на отдельной строке...

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingRepository.getBookingsByItem_IdOrderByStart(itemId).stream()
Помимо того что получился ужастный ифак... нужно, как я уже писал, возложить это на плечи БД, построив нужный тебе запрос.

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            return itemRepository.search(adaptedQuery).stream()
Тут почти всё хорошо...
Тут ты правильно возложил поиск на БД (можно было бы и приводить к нижнему регистру в базе)

но else в коде лишнее

```
    public List<ItemDto> search(String query) {
        if (query.isEmpty()) {
            return new ArrayList<>();
        }

        return itemRepository.search(query.toLowerCase()).stream()
                             .map(ItemMapper::toItemDto)
                             .collect(Collectors.toList());
    }
```

2022-11-09 18:24 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.findById(itemId).isEmpty()) {
Ну и все повторяющиеся места я не комментирую, я думаю ты понимаешь что надо рефакторить везде...

2022-11-10 06:39 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "start_date")
1. готово

2022-11-10 08:11 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    start_date datetime,
2. готово

2022-11-10 08:12 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    status     varchar(255),
3. согласен

2022-11-10 08:13 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    description  varchar(512),
4. добавил

2022-11-10 08:13 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    description  varchar(255)                            NOT NULL,
5. добавил

2022-11-10 08:13 UTC, Konkovmax commented on src/main/resources/schema.sql
> +    created      date,
6. исправил

2022-11-10 08:15 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @ManyToOne()
7. готово

2022-11-10 08:24 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.getAll(userId, state, false);
но получается, тогда надо либо скопировать такой же код в ещё один метод, либо создать третий метод с общим кодом, который будут вызывать getAllUser и getAllOwner, по сути просто передавая туда этот флаг....

2022-11-10 08:25 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private void throwIfNotValid(BookingIncomeDto booking) throws BadRequestException {
9. Писал.... тут просто нет смайликов, чтобы обозначить печаль, что упустил это

2022-11-10 09:17 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (userRepository.findById(userId).isEmpty()) {
10. заменил, но куда впихнуть log.warn не придумал(

2022-11-10 10:41 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        try {
11. Т.к. именно такой эксепшн нам для постмана нужен, то я смог предумать это в отдельный метод вынести. А каких-то готовых решений для такой проверки я не нашёл(  в теории можно было через аррэй и стрим проверить значения, но это тоже так себе выглядело...

2022-11-11 01:11 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .filter(bookingStatus)
12. Достаю не всё, но один фильтр всё-таки оставил, чтобы предикаты не убирать. Просто, когда я это всё придумал, мне это показалось такой чудесной идеей, минимум кода и т.п. Но теперь я уже понял, что класность идеи была преувеличена

2022-11-11 01:36 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/UnsupportedStatusException.java
> +public class UnsupportedStatusException extends RuntimeException {
13. я просто долго бился с постманом, который хотел получить сообщение конкретного вида, ни шаг вправо ни в лево.

2022-11-11 01:40 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/exception/ErrorHandlingControllerAdvice.java
> +        log.info("400 Bad Request Error", exception.getMessage(), exception);
14. так я и не знал, что так можно

2022-11-11 01:46 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.findById(userId).get());
15. переделал

2022-11-11 01:47 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(itemRepository.save(ItemMapper.toItem(item)));
16. надеюсь переделал как надо....

2022-11-11 04:37 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            return itemRepository.search(adaptedQuery).stream()
18. там в постмане опять же надо пустой запрос возвращать. Или это всё равно можно без else?

2022-11-11 04:49 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.findById(itemId).isEmpty()) {
19. так-то да, но то что напомнил - спасибо

2022-11-11 05:02 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingRepository.getBookingsByItem_IdOrderByStart(itemId).stream()
17. переделал, но не совсем так как хотелось получилось. Enumчерез запросный метод не заработал

2022-11-11 20:03 UTC, FanaticFiz requested changes
Давай еще одну итерацию.

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  package ru.practicum.shareit.booking;
У тебя в последнем коммите залетели файлы базы данных. 
Они должны быть добавлены в `gitignore`

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "end_date")
Я тебе тут как бы намекал что даты логично было бы сделать `NOT NULL`

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //как сюда ещё логирование ввернуть - что-то не нашёл... или это как-то подругому делается?
Показываю: 

```
    public List<BookingDto> getAllForUser(int userId, String stateIncome) {
        userRepository.findById(userId)
                      .orElseThrow(() -> {
                          log.warn("user not found");
                          
                          throw new NotFoundException(format("User with id: %s not found", userId));
                      });

        return bookingRepository.getBookingByBooker_Id(userId).stream()
                                .filter(bookingStatus(stateIncome))
                                .map(BookingMapper::toBookingDto)
                                .sorted((x1, x2) -> x2.getStart().compareTo(x1.getStart()))
                                .collect(Collectors.toList());
    }
```

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        itemRepository.findById(itemId).orElseThrow(() -> new NotFoundException(String.format(
Выделяй каждую новую операцию в цепочке на новую строку...

```
        itemRepository.findById(itemId)
                      .orElseThrow(() -> new NotFoundException(format("Item with id: %s not found", itemId)));
```

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!itemRepository.findById(itemId).orElseThrow().getAvailable()) {
Вот это: 

```
itemRepository.findById(itemId).orElseThrow()
```

Повторяется 3-и раза! Зачем ты сделал запрос в базу три раза?!

`Item item = itemRepository.findById(itemId).orElseThrow();`
И работаешь с `item`

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingRepository.findById(bookingId).orElseThrow(() -> new NotFoundException(String.format(
Тут тоже...

`bookingRepository.findById(bookingId).orElseThrow()`

3-и раза пишешь длинный сложный код и ходишь в базу с запросами вместо одного!

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if ((bookingRepository.findById(bookingId).orElseThrow().getBooker().getId() != userId) &&
Не оставляй `.orElseThrow()` всегда бросай свой ексепшн и поясняй что и почему не найдено.

К тому же когда ты так начнешь писать тебе будет больно делать это несколько раз подряд, как ты любишь )))) и ты быстрее поймешь что ты делаешь что-то не так!

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        try {
Если тесты предусматривают именно такой ексепшн то конечно подстраиваемся под спецификацию...

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(x -> x.getOwner().getId() == userId)
Что тут пошло не так? 
Вроде же должен быть простой запрос в БД чтобы не пришлось потом фильтровать по владельцу!

2022-11-11 20:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            return itemRepository.search(adaptedQuery).stream()
Ну да, код работать должен так же как и твой, только без `else`

2022-11-12 12:13 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  package ru.practicum.shareit.booking;
1. готово

2022-11-12 12:15 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "end_date")
я так понял, что нотнал надо то, что в базе нотнал. Ну и тут я решил, что может быть бронирование без дат. Типа я хочу дрель, картину повесить, но конкретные даты не важны

2022-11-12 12:16 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //как сюда ещё логирование ввернуть - что-то не нашёл... или это как-то подругому делается?
3. круто....

2022-11-12 12:26 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        itemRepository.findById(itemId).orElseThrow(() -> new NotFoundException(String.format(
4.поправил

2022-11-12 12:29 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!itemRepository.findById(itemId).orElseThrow().getAvailable()) {
5. вроде логично, а не заметил

2022-11-12 12:32 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if ((bookingRepository.findById(bookingId).orElseThrow().getBooker().getId() != userId) &&
7. хороший способ))))

2022-11-12 12:33 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingRepository.findById(bookingId).orElseThrow(() -> new NotFoundException(String.format(
6. готово

2022-11-12 12:42 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(x -> x.getOwner().getId() == userId)
8. исправил

2022-11-12 13:29 UTC, Konkovmax commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(x -> x.getOwner().getId() == userId)
9. почему-то в последнем твоём комментарии про else я не могу отвечать... пишу здесь. Без элс работает, тесты не проходит

2022-11-12 16:12 UTC, FanaticFiz approved these changes

2022-11-17 01:55 UTC, merged