Add docker
Konkovmax/java-shareit pull request #4
Opened 2022-12-08 16:18 UTC by Konkovmax

2022-12-09 19:06 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-09 19:06 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +package ru.practicum.shareit.booking.dto;
Файлы из `db/` должны быть выпилены из кода. В игнор они уже добавлены.

2022-12-09 19:06 UTC, FanaticFiz commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Мусор!
Да и проперти файл мог бы быть в YAML формате

2022-12-09 19:06 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                        PageRequest.of((size > from) ? 0 : from / size, size, Sort.by("id"))).stream()
Вынести бы на уровень контроллера формирование из size/from объекта `Pageable`
Там и валидацию параметров можно провести.

2022-12-09 19:06 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.getItemByOwner_Id(userId,
В `ItemRepository` с прошлого раза не причесан SQL запрос.
Оформляй запросы... служебные слова пиши в верхнем регистре: `SELECT`

2022-12-10 01:55 UTC, Konkovmax commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +package ru.practicum.shareit.booking.dto;
убрал

2022-12-10 02:00 UTC, Konkovmax commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
убрал

2022-12-10 02:01 UTC, Konkovmax commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
просто это был шаблон от практикума... Думал это тут так и надо....

2022-12-10 05:22 UTC, Konkovmax commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                        PageRequest.of((size > from) ? 0 : from / size, size, Sort.by("id"))).stream()
перенес, валидацию добавил

2022-12-10 05:25 UTC, Konkovmax commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.getItemByOwner_Id(userId,
исправил

2022-12-10 07:17 UTC, FanaticFiz approved these changes

2022-12-10 07:17 UTC, FanaticFiz commented on server/src/main/resources/application.properties
> +server.port=9090
Вот не напишешь в одном месте и всё... не вспомнят что есть еще один конфиг! )))

2023-02-11 01:52 UTC, merged